/*
 * IncludeDrawing.java
 *
 * Created on June 14, 2010, 11:03 AM
 */

package javands.ui;

import javax.swing.*;

import ensdfparser.nds.control.DrawingControl;
import ensdfparser.nds.control.NDSControl;
import javands.main.Run;

/**
 * A pop-up box that asks the user how many pages are in any drawing that they 
 * try to include that was not generated during this run of the code
 * @author scott
 */
public class IncludeDrawing extends javax.swing.JDialog {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Run r;
    int nPages;
    boolean portrait;
    boolean drawingAdded;
    DrawingControl drw;
    
    /** Creates new form IncludeDrawing */
    public IncludeDrawing(java.awt.Frame parent, boolean modal,Run r_t,DrawingControl d) {
        super(parent, modal);
        r=r_t;
        initComponents();
        portrait=true;
        drawingAdded=false;
        drw=d;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageNo = new javax.swing.JLabel();
        pageField = new javax.swing.JTextField();
        landscapeBox = new javax.swing.JCheckBox();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pageNo.setText("Number of Pages: ");

        pageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageFieldActionPerformed(evt);
            }
        });

        landscapeBox.setText("Landscape?");
        landscapeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landscapeBoxActionPerformed(evt);
            }
        });

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(pageNo)
                        .addGap(59, 59, 59)
                        .addComponent(pageField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(landscapeBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(OK)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNo))
                .addGap(18, 18, 18)
                .addComponent(landscapeBox)
                .addGap(18, 18, 18)
                .addComponent(OK)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageFieldActionPerformed
        int i=0;
        boolean wrongFormat=false;
        try{
            nPages=Integer.parseInt(pageField.getText());
        }catch(Exception e){
        	wrongFormat=true;
        }
        
        if(wrongFormat || nPages<0)
        	JOptionPane.showMessageDialog(this,"Please enter a positive,integer number");
        
        nPages=i;
        

        
    }//GEN-LAST:event_pageFieldActionPerformed

    private void landscapeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landscapeBoxActionPerformed
        portrait=!landscapeBox.isSelected();
    }//GEN-LAST:event_landscapeBoxActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        drw.setDrawn(true);
        drw.setPortrait(portrait);
        
        boolean wrongFormat=false;
        
        try{
            nPages=Integer.parseInt(pageField.getText());
        }catch(Exception e){
        	wrongFormat=true;
        }
        
        //debug
        //System.out.println("In includeDrawing: line 155: nPages="+nPages+" wrongFormat="+wrongFormat);
        
        if(wrongFormat || nPages<0)
        	JOptionPane.showMessageDialog(this,"Please enter a positive,integer number");
        else{
            drw.setPages(nPages);        
            drawingAdded=true;
            NDSControl.isBandSettingModified=true;
        	dispose();
        }

    }//GEN-LAST:event_OKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if(!drawingAdded){
            JOptionPane.showMessageDialog(this,"You did not hit OK, no drawing will be added");
        }
    }//GEN-LAST:event_formWindowClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JCheckBox landscapeBox;
    private javax.swing.JTextField pageField;
    private javax.swing.JLabel pageNo;
    // End of variables declaration//GEN-END:variables
    
}
