/*
 * masterFrame.java
 *
 * Created on May 10, 2010, 9:38 AM
 */

package javands.ui;

import java.io.*;

import javax.swing.*;

import java.util.Vector;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EtchedBorder;

import java.awt.Insets;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.text.DefaultCaret;

import ensdfparser.nds.config.NDSConfig;
import ensdfparser.nds.control.NDSControl;
import ensdfparser.nds.ensdf.MassChain;

import javax.swing.event.CaretListener;
import javax.swing.event.CaretEvent;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.border.TitledBorder;
import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import javax.swing.border.BevelBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.MatteBorder;
import javax.swing.border.EmptyBorder;

/**
 * The top-level user interface 
 * @author scott
 */
@SuppressWarnings("unused")
public class test extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	MassChain data;//all of the data in the file
    EnsdfWrap [] ensw;//wrappers for all of the endsfs in the file
    boolean isFileLoaded;
    boolean isFileProcessed;
    boolean isControlLoaded;
    javands.main.Run run;
    File dataFile;
    
    public test() {

        isFileLoaded=false;
        isControlLoaded=false;
        isFileProcessed=false;
        
        initComponents();
        
        run=new javands.main.Run(textArea);
        pathField.setText(javands.main.Setup.outdir);

        data=new MassChain();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JToggleButton();
        pathLabel = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        settingButton = new javax.swing.JToggleButton();
        settingButton.setToolTipText("view/modify control and band settings for individual dataset");
        settingButton.setEnabled(false);
        tableButton = new javax.swing.JToggleButton();
        tableButton.setToolTipText("<HTML>create tables with auto settings by default, unless control is manually set.<br>double click to run also shell script to create PDF file.</HTML>");
        controlButton = new javax.swing.JButton();
        controlButton.setToolTipText("load a control file for manual display settings for tables and figures");
        controlButton.setEnabled(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadButton.setText("Load ENSDF File");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        pathLabel.setText("Output path:");

        pathField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pathFieldPropertyChange(evt);
            }
        });
        pathField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pathFieldKeyReleased(evt);
            }
        });

        settingButton.setText("Control Settings");
        settingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButtonActionPerformed(evt);
            }
        });

        tableButton.setText("Create Tables");
        
        //tableButton.addActionListener(new java.awt.event.ActionListener() {
        //    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //        tableButtonActionPerformed(evt);
        //    }
        //});
        
        tableButton.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent evt) {
        		tableButtonMouseClicked(evt);
        	}
        });
        
        controlButton.setText("Load control file");
        controlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlButtonActionPerformed(evt);
            }
        });
        
        controlCheckBox = new JCheckBox("use control file");
        controlCheckBox.setToolTipText("use a control file for manual settings");
        controlCheckBox.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
                controlCheckBoxStateChanged(e);
        	}
        });
     
        settingCheckBox = new JCheckBox("set band & control");
        settingCheckBox.setToolTipText("select band and set control for individual dataset");
        settingCheckBox.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
                settingCheckBoxStateChanged(e);
        	}
        });
        
        scrollPane = new JScrollPane();
        //scrollPane.setViewportBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null), "message", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED),"message"));
        scrollPane.setToolTipText("display the processing status and message.");
        
        btnBrowse = new JButton("Browse");
        btnBrowse.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		browseButtonActionPerformed(evt);
        	}
        });
        
        panel = new JPanel();
        panel.setBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null), "Global Settings", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(59, 59, 59)));
        
        manual_label = new JLabel("<HTML><center>Manual<br>Mode</center></HTML>");
        manual_label.setBorder(null);
        manual_label.setForeground(SystemColor.windowText);
        manual_label.setBackground(UIManager.getColor("ArrowButton.background"));
        
        
        
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(0)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 600, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(pathLabel)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(pathField, GroupLayout.PREFERRED_SIZE, 446, GroupLayout.PREFERRED_SIZE)
        					.addGap(4)
        					.addComponent(btnBrowse, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(loadButton, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        						.addComponent(tableButton, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(manual_label, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(settingCheckBox)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(settingButton, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(controlCheckBox)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(controlButton, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 600, GroupLayout.PREFERRED_SIZE)))
        			.addGap(4))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(loadButton)
        						.addComponent(controlButton)
        						.addComponent(controlCheckBox, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(settingButton)
        							.addComponent(settingCheckBox, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        						.addComponent(tableButton))
        					.addGap(6))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(manual_label, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        					.addGap(15)))
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(pathField, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBrowse)
        				.addComponent(pathLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE))
        );
        
        drawingCheckBox = new JCheckBox("include all drawings");
        
                drawingCheckBox.setSelected(true);
                
                drawingCheckBox.addItemListener(new ItemListener() {
                	public void itemStateChanged(ItemEvent e) {
                		drawingCheckBoxStateChanged(e);
                	}
                });
                drawingCheckBox.setToolTipText("<html> include all band and level/decay drawings in Adopted and individual data sets.<br>If not checked, only band drawings in Adopted and level/decay drawings in individual data sets are included.</html> ");
                
                refCheckBox = new JCheckBox("include reference list");
                refCheckBox.setToolTipText("print reference list at the end of the output");
                nodrawingCheckBox = new JCheckBox("include no drawings");
                nodrawingCheckBox.setSelected(false);
                
                nodrawingCheckBox.addItemListener(new ItemListener() {
                	public void itemStateChanged(ItemEvent e) {
                		nodrawingCheckBoxStateChanged(e);
                	}
                });
                nodrawingCheckBox.setToolTipText("Do not include any drawings");
                
                        
                        suppressCheckBox = new JCheckBox("suppress all \"S\" records");
                        suppressCheckBox.setSelected(true);
                        suppressCheckBox.addItemListener(new ItemListener() {
                        	public void itemStateChanged(ItemEvent e) {
                        		suppressCheckBoxStateChanged(e);
                        	}
                        });
                        suppressCheckBox.setToolTipText("suppress S records in all data sets");
                
                includeTitleCheckBox = new JCheckBox("include title in reference");
                includeTitleCheckBox.setEnabled(false);
                
                btnNewButton = new JButton("More");
                GroupLayout gl_panel = new GroupLayout(panel);
                gl_panel.setHorizontalGroup(
                	gl_panel.createParallelGroup(Alignment.LEADING)
                		.addGroup(gl_panel.createSequentialGroup()
                			.addGap(2)
                			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
                				.addComponent(drawingCheckBox)
                				.addComponent(nodrawingCheckBox, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
                				.addComponent(refCheckBox)
                				.addComponent(suppressCheckBox, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE))
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
                				.addComponent(includeTitleCheckBox)
                				.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
                			.addGap(24))
                );
                gl_panel.setVerticalGroup(
                	gl_panel.createParallelGroup(Alignment.LEADING)
                		.addGroup(gl_panel.createSequentialGroup()
                			.addGap(3)
                			.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
                				.addComponent(refCheckBox)
                				.addComponent(drawingCheckBox)
                				.addComponent(includeTitleCheckBox))
                			.addGap(3)
                			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
                				.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
                					.addComponent(suppressCheckBox, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                					.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                				.addComponent(nodrawingCheckBox, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                			.addContainerGap())
                );
                panel.setLayout(gl_panel);
                refCheckBox.addItemListener(new ItemListener() {
                	public void itemStateChanged(ItemEvent e) {
                        refCheckBoxStateChanged(e);
                	}
                });

        groupLayout.setHonorsVisibility(false);
        
        textArea = new JTextArea();
        //textArea.addCaretListener(new CaretListener() {
        //	public void caretUpdate(CaretEvent e) {
        //		textArea.update(textArea.getGraphics());
        //		scrollPane.update(scrollPane.getGraphics());
        //	}
       // });
        
		textArea.setMargin(new Insets(5,5,5,5));
		textArea.setEditable(false);

		DefaultCaret caret = (DefaultCaret)textArea.getCaret();
		caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
		//caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

		//PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));
		//System.setOut(printStream);
		
		scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
		scrollPane.add(textArea);
        scrollPane.setViewportView(textArea);

        getContentPane().setLayout(groupLayout);
        
        pack();
		textArea.setVisible(true);
        scrollPane.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    
    private void resetUI(){
    	drawingCheckBox.setSelected(true);
    	nodrawingCheckBox.setSelected(false);
    	refCheckBox.setSelected(false);
    	suppressCheckBox.setSelected(true);
    	
    	controlCheckBox.setSelected(false);
    	controlButton.setEnabled(false);
    	
    	settingCheckBox.setSelected(false);
    	settingButton.setEnabled(false);
    	
    	
    	   	
    }
    
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed

         isFileLoaded=false;
         isFileProcessed=false;
         try{
             run.clear();
             NDSControl.reset();
             resetUI();
             
             //JFileChooser fc=new JFileChooser();
             JFileChooser fc;
             try {
                 fc = new JFileChooser(".");
              }catch (Exception e) {
                 fc = new JFileChooser(".", new RestrictedFileSystemView());
              }
                if(javands.main.Setup.filedir!=null)
                    fc.setCurrentDirectory(new File(javands.main.Setup.filedir));
                
                int ret=fc.showOpenDialog(this);
                if(ret==JFileChooser.APPROVE_OPTION){
                    javands.main.Setup.filedir=fc.getCurrentDirectory().toString();
                    javands.main.Setup.save();
                    data.clear();
                    dataFile=fc.getSelectedFile();
                    
                    run.printMessage("Loading file: "+dataFile.getName());
                    data.load(dataFile);
                    run.printMessage("Done loading");
                    
                    int n=data.nENSDF();

                    ensw=new EnsdfWrap[n];
                    for(int i=0;i<n;i++){
                        ensdfparser.nds.ensdf.EnsdfTableData etd=data.getETD(i);
                        ensw[i]=new EnsdfWrap(etd);
                    }
                    
                    isFileLoaded=true;
                }
               
            }catch(Exception e){
            	String message="Error when loading file! Please check the input file:"+dataFile.getName();
                JOptionPane.showMessageDialog(this,message);
                run.printMessage("***"+message);
                run.printMessage("***"+e.getMessage());
                e.printStackTrace(); 
            	               
            }

    }//GEN-LAST:event_loadButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {

        try{
            
            //JFileChooser fc=new JFileChooser();
            JFileChooser fc;
            try {
                fc = new JFileChooser(".");            
             }catch (Exception e) {
                fc = new JFileChooser(".", new RestrictedFileSystemView());
             }

            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setApproveButtonText("Select");
            fc.setApproveButtonToolTipText("Select this directory");
            
            if(javands.main.Setup.outdir!=null)
                fc.setCurrentDirectory(new File(javands.main.Setup.outdir));
            
            int ret=fc.showOpenDialog(this);
            if(ret==JFileChooser.APPROVE_OPTION){
                //nds.Setup.outdir=fc.getSelectedFile().toString();
            	
            	File file = fc.getSelectedFile();
            	javands.main.Setup.outdir=file.getAbsolutePath();
            	
                System.out.println();
                javands.main.Setup.save();
                
                pathField.setText(javands.main.Setup.outdir);
            }
            
           
        }catch(Exception e){
            //e.printStackTrace();
           	String message="Error when selecting output path!";
           	JOptionPane.showMessageDialog(this,message);
           	run.printMessage(message);           	                         
        }

   }
    
	private void reloadFile(){
    	if(dataFile==null)
    		return;
    	
    	try{
    		run.clear();
            data.clear();
            data.load(dataFile);

            int n=data.nENSDF();

            ensw=new EnsdfWrap[n];
            for(int i=0;i<n;i++){
            	ensdfparser.nds.ensdf.EnsdfTableData etd=data.getETD(i);
                ensw[i]=new EnsdfWrap(etd);
            }
            
            isFileLoaded=true;
            
    	}catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e);
            
        }
    	
    }
    
    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingButtonActionPerformed
      
        if(!isFileLoaded){
            JOptionPane.showMessageDialog(this,"You should load a file before trying to setting control and/or creating bands");
            return;
        }
        MainSettingFrame settingFrame=new MainSettingFrame(data,ensw,run);
        settingFrame.setTitle("Band and Control Settings");
        settingFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        settingFrame.setVisible(true);
        
        //notes which dataset need to have bands drawn for them
        
    }//GEN-LAST:event_settingButtonActionPerformed

    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed

        if(!isFileLoaded){
            JOptionPane.showMessageDialog(this,"You should load a file before trying to create tables");
            return;
        }
        else if(controlCheckBox.isSelected() && !isControlLoaded){
        	 JOptionPane.showMessageDialog(this,"Control file is not loaded and automatic settings will be used.");
        	 NDSControl.autoAdjust=true;
        }

        if(refCheckBox.isSelected())
        	NDSControl.hasReference=true;
        else
        	NDSControl.hasReference=false;
        
        if(drawingCheckBox.isSelected()){
        	NDSControl.includeAllDrawings=true;
        	NDSControl.nodrawing=false;
        }
        else
        	NDSControl.includeAllDrawings=false;
        
        if(nodrawingCheckBox.isSelected()){
        	NDSControl.nodrawing=true;
        	NDSControl.includeAllDrawings=false;
        }
        else
        	NDSControl.nodrawing=false;
        
        if(suppressCheckBox.isSelected())
        	NDSControl.showSuppressed=false;
        else
        	NDSControl.showSuppressed=true;
        
        boolean validOutdir=true;
        String message="";
        if(javands.main.Setup.outdir.trim().length()==0){
        	message="Error: output path is empty. ";           
        	validOutdir=false;
        }else{ 
            File f=new File(javands.main.Setup.outdir.trim());
        	if(!f.exists()){
        		message="Error: output path does not exist. ";
            	validOutdir=false;
        	}
        }
        
        if(!validOutdir){
        	message+="Please specify output path.";
        	run.printMessage(message);
            JOptionPane.showMessageDialog(this, message);
            return;
        }
        
        //default Config.latex is already set when the file is loaded
        //Config.latex=nds.Setup.outdir+run.dirSeparator()+run.getDefaultOutputFilename()+".tex";
        
        try{
        	//tableControl of each etd (dataset) in data will be changed and set in "writeLatex".
        	//So every time the "tableButton" is clicked, the data should be reloaded to reset all tableControl 
        	//to default settings
        	if(isFileProcessed && NDSControl.autoAdjust && !NDSControl.isTableControlModified && !NDSControl.isBandSettingModified)//re-process the same file 
        		reloadFile();
        	
        	run.clear();
        	
        	run.setData(data);
            run.writeLatex(NDSConfig.latex,data);
            isFileProcessed=true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tableButtonActionPerformed

    private void tableButtonMouseClicked(java.awt.event.MouseEvent evt) {

    	String message="";
    	
        if(!isFileLoaded){
            JOptionPane.showMessageDialog(this,"You should load a file before trying to create tables");
            return;
        }
        else if(controlCheckBox.isSelected() && !isControlLoaded){
        	 JOptionPane.showMessageDialog(this,"Control file is not loaded and automatic settings will be used.");
        	 NDSControl.autoAdjust=true;
        }

        if(refCheckBox.isSelected())
        	NDSControl.hasReference=true;
        else
        	NDSControl.hasReference=false;
        
        if(drawingCheckBox.isSelected()){
        	NDSControl.includeAllDrawings=true;
        	NDSControl.nodrawing=false;
        }
        else
        	NDSControl.includeAllDrawings=false;
        
        if(nodrawingCheckBox.isSelected()){
        	NDSControl.nodrawing=true;
        	NDSControl.includeAllDrawings=false;
        }
        else
        	NDSControl.nodrawing=false;
        
        if(suppressCheckBox.isSelected())
        	NDSControl.showSuppressed=false;
        else
        	NDSControl.showSuppressed=true;
        
        
        boolean validOutdir=true;
        if(javands.main.Setup.outdir.trim().length()==0){
        	message="Error: output path is empty. ";           
        	validOutdir=false;
        }else{ 
            File f=new File(javands.main.Setup.outdir.trim());
        	if(!f.exists()){
        		message="Error: output path does not exist. ";
            	validOutdir=false;
        	}
        }
        
        if(!validOutdir){
        	message+="Please specify output path.";
        	run.printMessage(message);
            JOptionPane.showMessageDialog(this, message);
            return;
        }
        
        //default Config.latex is already set when the file is loaded
        //Config.latex=nds.Setup.outdir+run.dirSeparator()+run.getDefaultOutputFilename()+".tex";
        
        try{
        	//tableControl of each etd (dataset) in data will be changed and set in "writeLatex".
        	//So every time the "tableButton" is clicked, the data should be reloaded to reset all tableControl 
        	//to default settings
        	if(isFileProcessed && NDSControl.autoAdjust && !NDSControl.isTableControlModified && !NDSControl.isBandSettingModified)//re-process the same file 
        		reloadFile();
        	
        	run.clear();

        	run.setData(data);
            run.writeLatex(NDSConfig.latex,data);

            isFileProcessed=true;
        }catch(Exception e){
        	message="Error when writing LaTex output file.";
        	run.printMessage(message);
            JOptionPane.showMessageDialog(this, message);
        }
         
        
        //run shell command to create PDF file
    	String script="NDS.bat";
    	String path=javands.main.Setup.outdir+"\\"+script;
    	String command="";
    	String os=System.getProperty("os.name").toLowerCase();
    	String outdir="";  
    	
    	if(os.contains("linux")||os.contains("mac")){
            script="NDS.sh";
            path=javands.main.Setup.outdir+"/"+script;
    	}
    	
    	message="\nTo create PDF file, please run the following script:\n";
    	message+=path;
    	
        try{
            if(evt.getClickCount()>=2){
          	
            	run.printMessage("\nRunning shell script to create PDF file.\n");
            	run.printMessage(path);
            	
            	if(os.contains("linux")||os.contains("mac")){

                    
                    String shell="/bin/bash";
                                                  		
                    File wd = new File(javands.main.Setup.outdir);
            		Process proc = null;
         		    proc = Runtime.getRuntime().exec(shell, null, wd);

            		if (proc != null) {
            		   BufferedReader in = new BufferedReader(new InputStreamReader(proc.getInputStream()));
            		   PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(proc.getOutputStream())), true);
            		   out.println("source "+script);
            		   out.println("pwd");
            		   out.println("exit");
         		       String line;
        		      
         		       while ((line = in.readLine()) != null) {
         		    	 //run.printMessage(line);
         		         //System.out.println(line);
         		       }
         		       //proc.waitFor();
         		       in.close();
         		       out.close();
         		       proc.destroy();
            		}            		
            	}
            	else if(os.contains("windows")){
                	Runtime rt = Runtime.getRuntime();
                	
                	//run cmd command in Java   
                	//
                	//method1: works only when run in the same drive, not work if script in a different drive
                	//
            		//command="cmd /c cd "+nds.Setup.outdir+"&& start "+script+"&exit";
            		//rt.exec(command);
  

            		/*
                	//
                	//method2: 
                	//
                	command="cmd /c "+script;             //If you do not want to start your process in it's separate console (that's what start does), 
                	                                      //you must wait with p.waitFor() or read it's input stream - otherwise it may silently fail.
            		Process proc=rt.exec(command,         //path to executable
            	            null,                                  // env vars, null means pass parent env
            	            new File(nds.Setup.outdir));

            	    InputStream is=proc.getInputStream();
            	    BufferedReader br= new BufferedReader(new InputStreamReader(is));
         		    PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(proc.getOutputStream())), true);
         		    out.println("exit");
         		   
            	    String line=new String();
            	    while ((line=br.readLine())!=null) {
            	    	//System.out.println (line);
            	    }
            	    br.close();
            	    proc.destroy();
            	    */
            	    
                	//
                	//method2:easiest way
                	//
                	command="cmd /c start "+script;       //start your process in it's separate console (that's what start does)
            		Process proc=rt.exec(command,         //path to executable
            	            null,                         // env vars, null means pass parent env
            	            new File(javands.main.Setup.outdir));  // working directory 

            	}
            	           	           	
            }else{
            	run.printMessage(message);
            }
            
        }catch(Exception e){
            run.printMessage(message);
        }
    }
    
    private void controlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlButtonActionPerformed

        Vector<String> v=new Vector<String>();
        JFileChooser fc;
        String s;
         try{
                //JFileChooser fc=new JFileChooser();
                
                try {
                    fc = new JFileChooser(".");
                 }catch (Exception e) {
                    fc = new JFileChooser(".", new RestrictedFileSystemView());
                 }
                 
                if(javands.main.Setup.filedir!=null)
                    fc.setCurrentDirectory(new File(javands.main.Setup.filedir));
                int ret=fc.showOpenDialog(this);
                if(ret==JFileChooser.APPROVE_OPTION){
                    javands.main.Setup.filedir=fc.getCurrentDirectory().toString();
                    javands.main.Setup.save();
                    
                    BufferedReader br=new BufferedReader(new FileReader(fc.getSelectedFile()));
                    while(true){
                        s=br.readLine();
                        if(s==null) break;
                        v.add(s);
                    }
                    NDSControl.setControl(v);
                    br.close();
                    isControlLoaded=true;
                }
                
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this,e);
            }

    }//GEN-LAST:event_controlButtonActionPerformed
    
    
    private void controlCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected()){
    		NDSControl.autoAdjust=false;
    		NDSControl.useControlFile=true;
    		controlButton.setEnabled(true);
    	    //resetButton.setEnabled(true);
    	}
    	else{
    		NDSControl.autoAdjust=true;
    		NDSControl.useControlFile=false;
    		controlButton.setEnabled(false);
    	    //resetButton.setEnabled(false);
    	}
    }
    
    private void settingCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected()){
    		settingButton.setEnabled(true);
    	}
    	else{
    		settingButton.setEnabled(false);
    		NDSControl.isModified=false;
    		NDSControl.isHeaderSettingModified=false;
    		NDSControl.isTableControlModified=false;
    	}
    }
    
    private void refCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected()){
    		NDSControl.hasReference=true;
    		includeTitleCheckBox.setEnabled(true);;
    	}
    	else{
    		NDSControl.hasReference=false;
    		includeTitleCheckBox.setEnabled(false);
    		includeTitleCheckBox.setSelected(false);
    	}
    }
    
    private void includeTitleCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected()){
    		NDSControl.includeRefTitle=true;
    	}
    	else{
    		NDSControl.includeRefTitle=false;
    	}
    }
    
    private void suppressCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected()){
    		NDSControl.showSuppressed=false;
    	}
    	else{
    		NDSControl.showSuppressed=true;
    	}
    }
    
    private void drawingCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected())
    		nodrawingCheckBox.setSelected(false);
    }    
    
    private void nodrawingCheckBoxStateChanged(ItemEvent e){
    	if(((JCheckBox)e.getSource()).isSelected())
    		drawingCheckBox.setSelected(false);
    } 
    
    private void pathFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pathFieldPropertyChange
        
    }//GEN-LAST:event_pathFieldPropertyChange

    private void pathFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFieldKeyReleased
        //specifies the path that output will be created in
        javands.main.Setup.outdir=pathField.getText();
        javands.main.Setup.save();
    }//GEN-LAST:event_pathFieldKeyReleased
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterFrame().setVisible(true);
            }
        });
    }
    
    public class CustomOutputStream extends OutputStream {
    	private JTextArea textArea;

    	public CustomOutputStream(JTextArea textArea) {
    		this.textArea = textArea;
    	}

    	@Override
    	public void write(int b) throws IOException {
    		// redirects data to the text area
            textArea.append(String.valueOf((char)b));
            // scrolls the text area to the end of data
            textArea.setCaretPosition(textArea.getDocument().getLength());
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton settingButton;
    private javax.swing.JButton controlButton;
    private javax.swing.JToggleButton loadButton;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JToggleButton tableButton;
    private javax.swing.JToggleButton resetButton;
    private JScrollPane scrollPane;
    private JTextArea textArea;
    private JCheckBox controlCheckBox;
    private JCheckBox settingCheckBox;
    private JCheckBox refCheckBox;
    private JCheckBox drawingCheckBox;
    private JCheckBox suppressCheckBox;
    private JButton btnBrowse;
    private JCheckBox nodrawingCheckBox;
    /**
     * @wbp.nonvisual location=301,379
     */

    private JPanel panel;
    private JCheckBox includeTitleCheckBox;
    private JButton btnNewButton;
    private JLabel manual_label;
}